# app/schemas/user_class.py

from pydantic import BaseModel, Field, field_validator

# --- Schema for data IN (used for POST requests) ---
class UserCreate(BaseModel):
    # Renamed 'id' to 'personal_id' here to prevent conflict with the DB's primary key 'id'
    personal_id: str = Field(..., min_length=11, max_length=11, alias="id")
    name: str = Field(..., max_length=50)
    surname: str = Field(..., max_length=50)
    email: str = Field(..., max_length=100)
    phone: str = Field(..., min_length=10, max_length=10)

    # Configuration for Pydantic to handle the 'id' alias in the JSON request
    class Config:
        populate_by_name = True

    @field_validator("phone", "personal_id")
    @classmethod
    def must_be_numeric(cls, v: str):
        if not v.isdigit():
            raise ValueError("ID and Phone must contain only digits")
        return v

    @field_validator("email")
    @classmethod
    def validate_email(cls, v: str):
        if "@" not in v or "." not in v:
            raise ValueError("Invalid email format")
        return v

# --- Schema for data OUT (used for response_model) ---
class User(UserCreate):
    id: int # The primary key auto-generated by the database

    # Required for SQLAlchemy objects
    class Config:
        from_attributes = True